spring.application.name=watchlist
spring.datasource.url=jdbc:postgresql://localhost:5432/moviewatchlist_db
spring.datasource.username=postgres
spring.datasource.password=2316

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080